### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by hxnan** [drael/GOnetstat#6]
code:
`d := GOnetstat.Tcp()`
env: centos7  go version go1.8.3 linux/amd64

error:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7fcc4a9f0c13]

runtime stack:
runtime.throw(0x894a30, 0x2a)
        /usr/lib/golang/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/lib/golang/src/runtime/signal_unix.go:274 +0x2db

goroutine 18 [syscall, locked to thread]:
runtime.cgocall(0x6dafe0, 0xc4200457f8, 0x400001)
        /usr/lib/golang/src/runtime/cgocall.go:131 +0xe2 fp=0xc4200457b0 sp=0xc420045770
os/user._Cfunc_mygetpwuid_r(0x0, 0xc4203b2e40, 0x7fcc5c000b20, 0x400, 0xc4202a6200, 0x0)
        os/user/_obj/_cgo_gotypes.go:178 +0x4d fp=0xc4200457f8 sp=0xc4200457b0
os/user.lookupUnixUid.func1.1(0x0, 0xc4203b2e40, 0x7fcc5c000b20, 0x400, 0xc4202a6200, 0xc4200458a0)
        /usr/lib/golang/src/os/user/lookup_unix.go:100 +0x175 fp=0xc420045850 sp=0xc4200457f8
os/user.lookupUnixUid.func1(0x10)
        /usr/lib/golang/src/os/user/lookup_unix.go:104 +0x50 fp=0xc420045890 sp=0xc420045850
os/user.retryWithBuffer(0xc42031c9f0, 0xc420045988, 0xc42031c9f0, 0xc42002a800)
        /usr/lib/golang/src/os/user/lookup_unix.go:253 +0x2b fp=0xc4200458f8 sp=0xc420045890
os/user.lookupUnixUid(0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/os/user/lookup_unix.go:105 +0x161 fp=0xc4200459c0 sp=0xc4200458f8
os/user.lookupUserId(0xc4202ba17c, 0x1, 0x876345, 0xc4202ba14e, 0x2)
        /usr/lib/golang/src/os/user/lookup_unix.go:86 +0x73 fp=0xc4200459f8 sp=0xc4200459c0
os/user.LookupId(0xc4202ba17c, 0x1, 0x0, 0xc4200a8b40, 0x2)
        /usr/lib/golang/src/os/user/lookup.go:21 +0x35 fp=0xc420045a30 sp=0xc4200459f8
github.com/drael/GOnetstat.getUser(0xc4202ba17c, 0x1, 0xc4202ba14e, 0x2)
        /home/hxn/go/src/github.com/drael/GOnetstat/gonetstat.go:184 +0x35 fp=0xc420045a68 sp=0xc420045a30
github.com/drael/GOnetstat.netstat(0x87692f, 0x3, 0x0, 0x7fcc63146e10, 0x0)
        /home/hxn/go/src/github.com/drael/GOnetstat/gonetstat.go:223 +0x329 fp=0xc420045c10 sp=0xc420045a68
github.com/drael/GOnetstat.Tcp(0x80c640, 0x0, 0xc420200510)
        /home/hxn/go/src/github.com/drael/GOnetstat/gonetstat.go:240 +0x36 fp=0xc420045c48 sp=0xc420045c10
main.getProcessPortMap(0xc4201c8f40)
```

**Comment by drael** [comment]
Hi,
I can't reproduce the error with the same environment:

```sh
$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
$ go version
go version go1.8.3 linux/amd64
```
Did you use some CGO flag? If I'm not mistake os/user needs cgo.

[]'s

**Comment by hxnan** [comment]
Yes, this is my build command.
`go build -o exe -ldflags '-linkmode "external" -extldflags "-static"'`
I want to build exe statically.

**Comment by drael** [comment]
Since os/user uses cgo try to build passing CGO_ENABLED=1
I succeed building with the following command
```sh
CGO_ENABLED=1 go build -a -ldflags '-extldflags "-static"' -installsuffix cgo -o exe tcp.go 
```
Ideally to have a more "static" binary you would use CGO_ENABLED=0 but it won't work since cgo is a dependency of the os std lib.
